#' Simulated Q-matrix
#'
#' The Q-matrix determines the relation between items and abilities.
#'
#' @source Generated by sampling each entry from \code{Bernoulli(0.35)}, but ensures
#' each item assess at least one latent ability
#' @format A data frame with 3 rows and 30 columns. If entry \code{[k,i] = 1},
#' then item \code{i} requires skill \code{k}.
#'
"q_matrix"
