#' Simulated Q-matrix
#' 
#' The Q-matrixx determines the relation between items and abilities.
#' 
#' @source Generated by sampling each entry from \code{Bernoulli(0.2)}.
#' @format A data frame with 3 rows and 15 columns. If entry \code{[k,i] = 1}, 
#' then item \code{i} requires skill \code{k}.
#' 
"q_matrix"