#' Response data
#'
#' Simulated response sets for 5000 students on an exam with 15 items.
#'
#' @source Generated by sampling from the probability of student success
#' on a given item according to the ML2P model.
#' @format A data frame with 15 columns and 5000 rows.
#' Entry \code{[j,i]} is 1 if student \code{j} answers item \code{i} correctly, and 0 otherwise.
#'
"responses"
