#' Simulated ability parameters
#' 
#' Three correlated ability parameters for 500 students.
#' 
#' @source Generated by sampling from a 3-dimensional multivariate Gaussian distribution
#'with mean 0 and covariance matrix \code{correlation_matrix.rda}.
#' @format A data frame with 500 rows and 3 columns. Each row represents a particular
#' student's three latent abilities.
#' 
"theta_true"